export default {
    COLOR_PRIMARY: '#F8E3E3',
    COLOR_SECONDARY: 'lightblue',
    COLOR_BLACK: 'black',
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_LARGE: 20,
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_BOLD: 800,
};