export default {
    FONT_SIZE_SMALL: 16,
    FONT_SIZE_MEDIUM: 20,
    FONT_SIZE_LARGE: 24,
    FONT_SIZE_DISPLAY: 32,
    FONT_WEIGHT_LIGHT: "200",
    FONT_WEIGHT_MEDIUM: "600",
    FONT_WEIGHT_BOLD: "800",
    DEFAULT_PADDING: 18,
};